env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".ts"
rules:
  semi:
    - error
    - always
  quotes:
    - error
    - single
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-explicit-any": 1
  "@typescript-eslint/no-inferrable-types":
    - warn
    -
      ignoreParameters: true
  "@typescript-eslint/no-unused-vars": warn
  no-underscore-dangle: off
  comma-dangle:
    - error
    - always-multiline
  import/extensions: off
  no-param-reassign:
    - error
    -
      props: false
  lines-between-class-members:
    - error
    - always
    -
      exceptAfterSingleLine: true
